language: r
r:
    - release
    - devel 
os:
    - linux
    - osx
matrix:
    exclude:
        r: devel
        os: osx
sudo: enabled
latex: false
warnings_are_errors: true
cran: https://cran.rstudio.com
cache:
  packages: true
  pip: true
  directories:
    - $HOME/.stack/
    - $HOME/.local/bin/
    - $HOME/Library/Caches/Homebrew
before_install:
    - bash ./.travis/install_system_dependencies.sh
    - ledger --version
    - hledger --version
    - bean-query --version
notifications:
  email:
    on_success: change
    on_failure: change
after_success:
    - Rscript -e 'covr::codecov()'
